name: DeathTpPlus
main: org.simiancage.DeathTpPlus.DeathTpPlus
version: 2.00
website: https://github.com/dredhorse/DeathTpPlus
authors: [Don Redhorse, orig. by. lonelydime]
description: Death commands including deathtp, deathnotify and deathstreaks.
softdepend: [Register,CraftIRC]

commands:
    deathtp:
        description: Teleports you back to your last death location
        permission: deathtpplus.deathtp
        usage: |
            /<command>
    streak:
        description: Lets you view your or other's kill/death streak.
        permission: deathtpplus.streak
        usage: |
            /<command> [player]
            Example: /<command> - Displays your streak.
            Example: /<command> lonelydime's - checks lonelydime's streak.
    deaths:
        description: Lets you view your or other's total deaths.
        permission: deathtpplus.deaths
        usage: |
            /<command> (username) (cause)
            Example: /<command> - Displays your total death count.
            Example: /<command> lonelydime - Displays total death count.
            Example: /<command> lonelydime creeper - checks lonelydime's deaths by creeper.
    kills:
        description: Lets you view your or other's total pvp kills.
        permission: deathtpplus.kills
        usage: |
            /<command> (username) (playername)
            Example: /<command> - Displays your total kill count.
            Example: /<command> dredhorse - Displays total kill count.
            Example: /<command> lonelydime dredhorse - prints times lonelydime killed dredhorse.

permissions:
    deathtpplus.*:
        description: Gives access to all DeathTpPlus commands
        children:
            deathtpplus.deathtp: true
            deathtpplus.streak: true
            deathtpplus.deaths: true
            deathtpplus.kills: true
            deathtpplus.worldtravel: true
    deathtpplus.deathtp:
        description: Gives access to the deathtp command
        default: op
    deathtpplus.streak:
        description: Gives access to the streak command
        default: op
    deathtpplus.deaths:
        description: Gives access to the deaths command
        default: op
    deathtpplus.kills:
        description: Gives access to the kills command
        default: op
    deathtpplus.worldtravel:
        description: Allows teleporting to another worlds death location
        default: op